{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "petclinic.fullname" . }}-default-deny
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "petclinic.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "petclinic.fullname" . }}-allow-ingress
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "petclinic.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressControllerNamespace }}
      ports:
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "petclinic.fullname" . }}-allow-egress
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "petclinic.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- if .Values.database.enabled }}
    - ports:
        - protocol: TCP
          port: {{ .Values.database.port }}
    {{- end }}
    {{- if .Values.networkPolicy.cilium.enabled }}
    - ports:
        - protocol: TCP
          port: 443
    {{- end }}
{{- end }}
